# This is a basic workflow to help you get started with Actions
name: enable_MDC_Plans

# Controls when the workflow will run
on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: {
  "clientId": "d91a4bc0-1945-47a7-b6b9-0e22efb6c499",
  "clientSecret": "fYm8Q~_YFjVJhmTz36tH7oDcFpDEl1WCK59UmaiG",
  "subscriptionId": "0f53b943-3fcd-4183-93d0-3ae290c48233",
  "tenantId": "a0378c20-d53d-404b-b995-33369b07ade3",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
}
      - run: |
          az webapp list --query "[?state=='Running']"
          
